version: '2'

services:
  uaa:
    image: '97musienko/test'
    ports:
    - 8080:8080
    depends_on:
      - db
    env_file:
      - service.env
  db:
    image: 'postgres'
    env_file:
      - db.env



